### ISSUE TITLE
Pest + Dusk + Sail

### ISSUE THREAD

**Issue by TheFehr** [stechstudio/laravel-visual-testing#7]
I am trying to get this setup with a new Laravel App.

I am using Laravel sail to develop in docker and I have Pest and Laravel Dusk setup and working. (`php artisan dusk --pest --without-percy` works perfectly)

Now I wanted to add this but when I run `php artisan dusk --pest` I receive this error message:
```
[percy] Config file not found
[percy] created build #3: https://percy.io/1e6dcf4c/esg-radar/builds/12960345
    Error: Failed to launch the browser process!
    /var/www/html/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


    TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
```

It seems that percy does not know anything about the remote selenium instance nor how to use it.
Do you see a way we could get this working? Or is this a lost cause?

**Comment by jszobody** [comment]
I don't know offhand. I don't use sail personally (still happy with valet) and I haven't used Pest much either. I'd happily take a PR if someone is able to troubleshoot this and provide a solution, but it's not something I'm likely to get to anytime soon.

**Comment by TheFehr** [comment]
I think we can close this, unless anyone else wants this to stay open.
I realized that there is not really the need to execute percy locally as this makes more sense on a ci.
And with github actions, after some trial and error it works perfectly now.

**Comment by jszobody** [comment]
That's great to hear. 👍
