### ISSUE TITLE
Plans on migrating from @percy/agent to @percy/cli

### ISSUE THREAD

**Issue by bgturner** [stechstudio/laravel-visual-testing#8]
I notice that the `@percy/agent` project is no longer supported and they are urging users to migrate to `@percy/cli`:

> This package has been deprecated
> Author message:
> 
> @percy/agent is no longer supported. Please upgrade to @percy/cli https://docs.percy.io/docs/migrating-to-percy-cli
>
> -- https://www.npmjs.com/package/@percy/agent

Are there any plans on upgrading `laravel-visual-testing` to use percy's new tooling?

**Comment by jszobody** [comment]
I don't have much time to work on it myself, but I'd happily review a Pull Request if you or anyone else wanted to take a stab at this?

**Comment by bgturner** [comment]
I'm new to the Laravel ecosystem, so I was hoping that you would be familiar enough with it for a quick fix! :)

I'll see if I can carve some time out to take a closer look!

**Comment by nathangross** [comment]
Following—would love to use this!

**Comment by royduin** [comment]
Just use the CLI directly in your actions: https://www.browserstack.com/docs/percy/ci-cd/github-actions and take screenshots with Dusk: https://laravel.com/docs/master/dusk#taking-a-screenshot
```
- name: Percy snapshots
  run: npx percy upload tests/Browser/screenshots
  env:
    PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```
